export const RECIPES_LOADING = "RECIPES_LOADING";
export const ADD_RECIPES = "ADD_RECIPES";
export const RECIPES_FAILED = "RECIPES_FAILED";

export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const BREAKFASTS_LOADING = "BREAKFASTS_LOADING";
export const ADD_BREAKFASTS = "ADD_BREAKFASTS";
export const BREAKFASTS_FAILED = "BREAKFASTS_FAILED";

export const LUNCHES_LOADING = "LUNCHES_LOADING";
export const ADD_LUNCHES = "ADD_LUNCHES";
export const LUNCHES_FAILED = "LUNCHES_FAILED";

export const DINNERS_LOADING = "DINNERS_LOADING";
export const ADD_DINNERS = "ADD_DINNERS";
export const DINNERS_FAILED = "DINNERS_FAILED";
